apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-test-oauth-test
  labels:
    codefresh.io/entity: integration-config
    codefresh.io/integration-type: issue.jira.oauth
    codefresh.io/integration-enabled-jira-write-back: 'true'
data:
  host_url: 'https://codefresh-io-sandbox-587.atlassian.net'
